triggers:
   - name: triggerv2sp1
     type: trigger
     version:
       counter: 6
       
   - name: triggerv2sp2
     type: trigger
     version:
       counter: 2
       
   - name: triggerv2sp3
     type: trigger
     version:
       counter: 19
       
   - name: triggerv2sp4
     type: trigger
     version:
       counter: 16
       
   - name: triggerv2sp5
     type: trigger
     version:
       counter: 4
       
   - name: triggerv2sp6
     type: trigger
     version:
       counter: 4
       
   - name: triggerv2sp7
     type: trigger
     version:
       counter: 9
       
   - name: triggerv2sp8
     type: trigger
     version:
       counter: 1
       
   - name: triggerv2sp9
     type: trigger
     version:
       counter: 1
       
   - name: triggerv2sp10
     type: trigger
     version:
       counter: 0
       
   - name: triggerv2sp11
     type: trigger
     version:
       counter: 0
       
   - name: triggerv2sp12
     type: trigger
     version:
       counter: 0
       
   - name: triggerv2sp13
     type: trigger
     version:
       counter: 0
       
   - name: triggerv2sp14
     type: trigger
     version:
       counter: 1
