triggers:
   - name: ed-tr1
     type: trigger
     version:
       counter: 0
       
   - name: ed-tr2
     type: trigger
     version:
       counter: 0
       
   - name: ed-tr3
     type: trigger
     version:
       counter: 0
       
   - name: ed-tr4
     type: trigger
     version:
       counter: 0
       
   - name: ed-tr5
     type: trigger
     version:
       counter: 0
       
   - name: ed-tr6
     type: trigger
     version:
       counter: 0
       
   - name: ed-tr7
     type: trigger
     version:
       counter: 0
       
   - name: ed-tr8
     type: trigger
     version:
       counter: 0
       
   - name: ed-tr9
     type: trigger
     version:
       counter: 0
       
   - name: ed-tr10
     type: trigger
     version:
       counter: 0
       
   - name: ed-tr11
     type: trigger
     version:
       counter: 0
       
   - name: ed-tr12
     type: trigger
     version:
       counter: 0
       
   - name: ed-tr13
     type: trigger
     version:
       counter: 0
       
   - name: ed-tr14
     type: trigger
     version:
       counter: 0
